# Generated by Django 4.1 on 2022-10-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='video'),
        ),
    ]
