# Generated by Django 4.1 on 2022-10-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0002_alter_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
