# Generated by Django 4.1 on 2022-10-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0003_alter_image_img_alter_image_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='video'),
        ),
    ]
