# Generated by Django 4.1 on 2022-10-31 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0004_alter_image_options_alter_image_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Galery',
        ),
    ]
