# Generated by Django 4.1 on 2022-10-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0010_album_tile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title', 'fecha']},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='tile',
            new_name='title',
        ),
    ]
