# Generated by Django 4.1 on 2022-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0012_alter_album_options_rename_title_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='album de imagenes', max_length=150),
        ),
    ]
