# Generated by Django 4.1 on 2022-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0014_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
