# Generated by Django 4.1 on 2022-10-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0016_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenes',
        ),
    ]
