# Generated by Django 4.1 on 2022-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaFotos', '0017_delete_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
